In [54]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [55]:
from plotly import __version__
print(__version__)

6.0.1

In [72]:
import cufflinks as cf

In [73]:
from plotly.offline import  download_plotlyjs,init_notebook_mode,plot,iplot

In [58]:
init_notebook_mode(connected=True)

In [14]:
cf.go_offline()

In [77]:
# Data
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [60]:
df.head()

          A         B         C         D
0  1.487115 -0.741964 -0.689808  0.633234
1 -0.862617  0.413433 -0.851276 -0.322240
2 -0.025398  0.892049 -0.063269 -0.235301
3 -0.005961 -0.917104  0.057192  0.181441
4 -0.412712  0.530743 -0.231436 -0.669753

In [61]:
df2 = pd.DataFrame({'Catagory':['A','B','C'],'Values':[32,43,50]})

In [62]:
df2.head()

  Catagory  Values
0        A      32
1        B      43
2        C      50

In [63]:
fig = px.line(df) # The course is old and some things need to be updated in this case use ploty experss to get the interactive image to show. 
fig.show()

In [64]:
# Create the figure
fig = px.scatter(df, x="A", y="B")

# Show the plot
fig.show()

In [65]:
figBar = px.bar(df2, x='Catagory', y='Values')
figBar.show()

In [66]:
df

           A         B         C         D
0   1.487115 -0.741964 -0.689808  0.633234
1  -0.862617  0.413433 -0.851276 -0.322240
2  -0.025398  0.892049 -0.063269 -0.235301
3  -0.005961 -0.917104  0.057192  0.181441
4  -0.412712  0.530743 -0.231436 -0.669753
..       ...       ...       ...       ...
95  0.542305 -0.566653 -0.073396  1.347921
96  0.932566  0.685712  0.166343 -0.530901
97 -2.207644 -1.076906 -0.469246  0.212439
98  1.364466 -1.185742  0.071484  0.282417
99  1.547982 -0.776443  1.081605  0.399858

[100 rows x 4 columns]

In [52]:
# 1. Create a grid of X and Y values
x = np.linspace(-5, 5, 50)
y = np.linspace(-5, 5, 50)
x_grid, y_grid = np.meshgrid(x, y)

# 2. Generate random "Z" data (a sin wave + random noise)
z = np.sin(np.sqrt(x_grid**2 + y_grid**2)) + np.random.normal(0, 0.1, x_grid.shape)

# 3. Create the Surface Plot
fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])

# 4. Style the layout
fig.update_layout(
    title='Random 3D Surface Plot',
    autosize=False,
    width=800,
    height=800,
    margin=dict(l=65, r=50, b=65, t=90),
    scene = dict(
        xaxis_title='X Axis',
        yaxis_title='Y Axis',
        zaxis_title='Z Axis'
    )
)

fig.show()

In [79]:
df2.iplot(kind='scatter', 
         x='A', 
         y='B', 
         mode='markers',
         title='My Interactive Scatter Plot',
         xTitle='X Axis Label',
         yTitle='Y Axis Label',
         theme='pearl',
         colors=['blue', 'red'])

KeyError: "None of ['A'] are in the columns"